using Content.Client.Message;
using Content.Client.Store.Ui;
using Content.Shared.FixedPoint;
using Content.Shared.Imperial.Medieval.Ships.ShipBuyTerminal;
using Content.Shared.Store;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client.Imperial.Medieval.Ships.ShipBuyTerminal;

[UsedImplicitly]
[GenerateTypedNameReferences]
public sealed partial class ShipBuyTerminalMenu : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private StoreWithdrawWindow? _withdrawWindow;
    private CurrencyPrototype? _currency;
    private readonly List<Button> _buyButtons = new();

    public event Action<BaseButton.ButtonEventArgs, int>? OnBuyOffer;
    public event Action<BaseButton.ButtonEventArgs, string, int>? OnWithdrawAttempt;

    private FixedPoint2 _balance;

    public ShipBuyTerminalMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        WithdrawButton.OnButtonDown += OnWithdrawButtonDown;
    }

    public void UpdateState(ShipBuyTerminalUpdateState state)
    {
        _balance = state.Balance;
        _currency = _prototype.TryIndex<CurrencyPrototype>(state.Currency, out var currency) ? currency : null;

        var balanceText = Loc.GetString(
            "store-ui-balance-display",
            ("currency", Loc.GetString("ship-buy-terminal-currency-name")),
            ("amount", state.Balance));

        BalanceInfo.SetMarkup(balanceText.Trim());

        PopulateOffers(state.GridOfferIds, state.Balance, state.PurchaseLocked);

        WithdrawButton.Disabled = state.Balance <= 0 || _currency == null || !_currency.CanWithdraw;
    }

    public void LockPurchaseButtons()
    {
        foreach (var button in _buyButtons)
        {
            button.Disabled = true;
        }
    }

    private void PopulateOffers(IReadOnlyList<string> offerIds, int balance, bool purchaseLocked)
    {
        OffersContainer.Children.Clear();
        _buyButtons.Clear();

        for (var i = 0; i < offerIds.Count; i++)
        {
            if (!_prototype.TryIndex<ShipGridOfferPrototype>(offerIds[i], out var offer))
                continue;

            var canBuy = balance >= offer.Cost;

            var entry = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(2, 3),
            };

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
            };

            var nameLabel = new Label
            {
                Text = Loc.GetString(offer.DisplayName),
                HorizontalExpand = true,
            };

            var costLabel = new Label
            {
                Text = $"{offer.Cost} {Loc.GetString("ship-buy-terminal-currency-name")}",
                MinWidth = 140,
                HorizontalAlignment = HAlignment.Right,
                Margin = new Thickness(8, 0),
            };

            var buyButton = new Button
            {
                Text = Loc.GetString("store-ui-buy-button"),
                Disabled = purchaseLocked || !canBuy,
                MinWidth = 60,
            };

            var offerIndex = i;
            buyButton.OnButtonDown += args => OnBuyOffer?.Invoke(args, offerIndex);
            _buyButtons.Add(buyButton);

            row.AddChild(nameLabel);
            row.AddChild(costLabel);
            row.AddChild(buyButton);
            entry.AddChild(row);

            if (!string.IsNullOrWhiteSpace(offer.DisplayDescription))
            {
                var descLabel = new RichTextLabel
                {
                    HorizontalExpand = true,
                    Margin = new Thickness(2, 1, 0, 0),
                };
                descLabel.SetMessage(
                    Loc.GetString(offer.DisplayDescription),
                    defaultColor: Color.FromHex("#AAAAAA"));
                entry.AddChild(descLabel);
            }

            OffersContainer.AddChild(entry);
        }
    }

    private void OnWithdrawButtonDown(BaseButton.ButtonEventArgs args)
    {
        if (_currency == null)
            return;

        if (_withdrawWindow != null && _withdrawWindow.IsOpen)
        {
            _withdrawWindow.MoveToFront();
            return;
        }

        _withdrawWindow = new StoreWithdrawWindow();
        _withdrawWindow.OpenCentered();
        _withdrawWindow.CreateCurrencyButtons(
            new Dictionary<ProtoId<CurrencyPrototype>, FixedPoint2> { { _currency, _balance } });
        _withdrawWindow.OnWithdrawAttempt += OnWithdrawAttempt;
    }

    public override void Close()
    {
        base.Close();
        _withdrawWindow?.Close();
    }
}
